# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jymPOL_VB2r4rcmpqVSeCtiQXYW80Wy_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

c = sns.load_dataset('car_crashes')
c.head()

c.info()

x=c.iloc[:,1:-1]
x.head()

y = c['total']
y[:3]

from sklearn.feature_selection import mutual_info_regression

score = mutual_info_regression(x,y)

score

len(score)

score

imp_fea = pd.DataFrame(score,columns=['scores'])

imp_fea

df_columns = pd.DataFrame(c.columns,columns=['features'])
df_columns

new_feat = pd.concat([imp_fea,df_columns],axis = 1)

new_feat

new_feat = new_feat.nlargest(20,'scores')

new_feat

new_feat.plot(kind='barh',x='features',y='scores')

from sklearn.feature_selection import RFE

from sklearn.linear_model import LinearRegression

lr =  LinearRegression()

rf_new = RFE(estimator=lr,n_features_to_select=5)

rf_new

rf_new.fit(x,y)

rf_new.n_features_

rf_new.estimator_

rf_new.support_

rf_new.ranking_

rf_new.fit_transform(x,y)

x.loc[:,rf_new.support_][:3]

from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor()

rfe_dt = RFE(estimator=dtr,n_features_to_select=5)
rfe_dt.fit(x,y)

from sklearn.feature_selection import SelectKBest

sk = SelectKBest(score_func=mutual_info_regression,k=5)
sk

sk.fit(x,y)

sk.scores_

final = pd.concat([pd.DataFrame(sk.scores_,columns=['score']),pd.DataFrame(x.columns,columns=['features'])],axis=1)
final[:]

final.nlargest(5,'score')

